[project]
name = "sign-language-translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gtts>=2.5.4",
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
    "pygame>=2.6.1",
    "streamlit>=1.45.0",
]
